### ISSUE TITLE
Animated Spalsh Screen

### ISSUE THREAD

**Issue by Shobu95** [Shobu95/Crebits#1]
Need an good animated Splash screen for the application. UI made using Jetpack Compose is acceptable but not necessary

**Comment by SiddyDevelops** [comment]
@Shobu95 I would like to solve this issue, can you please assign it me ? Thank you.

**Comment by Shobu95** [comment]
Sure brother. Here you go. Happy Hacking

**Comment by SiddyDevelops** [comment]
@Shobu95 Sir I have generated a PR #8. Please review it. Also please add ```hactober-accepted``` label. Thank you.

**Comment by Shobu95** [comment]
sure let me review it and i'll mark it as accepted.

**Comment by SiddyDevelops** [comment]
Sir please review #9 . Thank you.

**Comment by Shobu95** [comment]
@SiddyDevelops Dear Siddharth, it seems i have reverted you PR by mistake and i cant seem to find the changes in my project. Can you make the same PR to develop again???? i'll be careful this time.

**Comment by SiddyDevelops** [comment]
@Shobu95 sir PR #12

**Comment by AliAzaz** [comment]
I have found one issue in splash screen.
  
  **Steps**
  
  - Open app
  - Press the home button while splash screen is loading.
  - It will automatically open the app that you just closed it.
