### ISSUE TITLE
Dynamic Toolbar for Add and Edit Screen

### ISSUE THREAD

**Issue by Shobu95** [Shobu95/crebits#4]
The toolbar text should change according to the state of the screen. i.e. 
for Add the text should be Add Crebit,
for Edit the text should be Edit Crebit

**Comment by Droyder7** [comment]
Hey, I want to work on this. Can you assign this to me?

**Comment by Shobu95** [comment]
Sure. Assigning it to you right now. 
Happy Hacking. 🤩

**Comment by Shobu95** [comment]
@Droyder7 any update on your contribution ???

**Comment by Droyder7** [comment]
Hey, sorry for the delay. I have generated a PR #13 for fixing this issue . Please review it

**Comment by Shobu95** [comment]
No worried @Droyder7 . Great Contribution. If you like my project, do give it a star. Happy Hacking.

**Comment by Droyder7** [comment]
Thanks @Shobu95. I have already starred this project of yours

**Comment by AliAzaz** [comment]
@Shobu95 is it still opened or not?

**Comment by Shobu95** [comment]
@AliAzaz PR for this issue has already been submitted. You can check other issues. Happy Hacking. :)
